apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app
type: Opaque
stringData:
  DB_HOST:     postgres-service.data.svc.cluster.local
  DB_PORT:     "5432"
  DB_NAME:     techsalary
  DB_USERNAME: watupa
  DB_PASSWORD: watupa_secret_2026
  JWT_SECRET:  jDR6g1+uLJWfi3hJ5T9mobjpyQrc+/NxIdeaSoQSo5U=
