apiVersion: v1
kind: ConfigMap
metadata:
  name: watupa-config
  namespace: watupa
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "watupa"
  DB_USERNAME: "watupa"
  # Password in Secret
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"
