apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: watupa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        image: watupa/identity-service:latest
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: watupa-config
        - secretRef:
            name: watupa-secret
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: watupa
spec:
  selector:
    app: identity-service
  ports:
  - port: 8001
    targetPort: 8001
