apiVersion: v1
kind: Secret
metadata:
  name: watupa-data-secret
  namespace: watupa-data
type: Opaque
data:
  DB_PASSWORD: d2F0dXBhMTIz  # base64 of watupa123

---

apiVersion: v1
kind: Secret
metadata:
  name: watupa-secret
  namespace: watupa-app
type: Opaque
data:
  DB_PASSWORD: d2F0dXBhMTIz  # base64 of watupa123
